#!/bin/sh

pkill -q -w picom 
pkill -q -w sxhkd
pkill -q -w polybar

# Start polybar
bash $HOME/.config/polybar/launch.sh &
feh --bg-fill $HOME/Pictures/leaves-2.jpg &	# Wallpaper handler
sxhkd &

xsetroot -cursor_name left_ptr

bspc monitor HDMI-A-0             -d 1 2 3 4 5 
bspc monitor eDP                  -d 1 2 3 4 5 

bspc config border_width          2  
bspc config window_gap            10

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle        false
bspc config focus_follows_pointer true

bspc config focused_border_color  "#BD93F9"
#bspc config normal_boder_color    "#282A36"
#bspc config active_border_color   "#BD93F9"
#bspc config presel_feedback_color "#50FA7B"

# Auto-Start
picom --experimental-backends -b &						# X11 Compositor
$HOME/.screenlayout/display.sh &			# Monitor handler
/usr/bin/numlockx on &
